/** @typedef {'indicator' | 'ea'} ToolType */

const MT5_REQ_EN =
  "MetaTrader 5 build 3000+, Windows or VPS. Allow Algo Trading and DLL imports if prompted.";
const MT5_REQ_KM =
  "MetaTrader 5 build 3000+ និង Windows/VPS។ បើក Algo Trading និង DLL imports ប្រសិនបើត្រូវការ។";

const IMAGES = [
  "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=960&q=80",
  "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=960&q=80",
  "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=960&q=80",
  "https://images.unsplash.com/photo-1642790551117-97e405cb55de?auto=format&fit=crop&w=960&q=80",
  "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=960&q=80",
];

/**
 * 17 MT5 tools for Trading Machenic catalog seed.
 * `seed_slug` matches optional file in scripts/seed-assets/tools/{seed_slug}.zip
 */
export const toolsData = [
  {
    seed_slug: "trade-journal-v2",
    name: "TradeJournal V2",
    type: "indicator",
    platform: "MT5",
    pricing: "free",
    version: "2.0.0",
    description_en:
      "Analyze closed trades from your MT5 history—win rate, R-multiple, session breakdown, and recurring mistakes in one panel.",
    description_km:
      "វិភាគប្រតិបត្តិការបិទពីប្រវត្តិ MT5—អត្រាឈ្នះ R-multiple តាមសម័យ និងកំហុសដដែលៗក្នុងបន្ទះតែមួយ។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en:
      "Attach to any chart. The panel reads deal history and groups stats by symbol, setup tag, and session.",
    how_it_works_km: "ភ្ជាប់លើគេហ។ បន្ទះអានប្រវត្តិ deal និងដាក់ស្ថិតិតាម symbol សម័យ និង setup។",
    key_features_en:
      "• Win rate & expectancy\n• Session and symbol filters\n• Export-friendly summary rows",
    key_features_km: "• អត្រាឈ្នះ និង expectancy\n• តម្រងតាមសម័យ និង symbol\n• សង្ខេបអាចនាំចេញបាន",
    usage_notes_en: "Refresh after closing trades. Use on a demo account first to verify timezone settings.",
    usage_notes_km: "ធ្វើបច្ចុប្បន្នភាពបន្ទាប់ពីបិទប្រតិបត្តិការ។ សាកល្បងនៅ demo ជាមុនសិន។",
    proof_of_testing_en: "Forward-tested on demo XAUUSD and EURUSD accounts over 8 weeks of manual journaling.",
    proof_of_testing_km: "សាកល្បង forward លើ demo XAUUSD និង EURUSD រយៈពេល ៨ សប្តាហ៍។",
    image_url: IMAGES[0],
  },
  {
    seed_slug: "bbma-model",
    name: "BBMA Model",
    type: "indicator",
    platform: "MT5",
    pricing: "free",
    version: "1.0.0",
    description_en:
      "Bollinger Bands + Moving Average confluence toolkit for BBMA-style structure, re-entry zones, and momentum shifts.",
    description_km:
      "ឧបករណ៍ BBMA—Bollinger Bands និង Moving Average សម្រាប់រចនាសម្ព័ន្ធ តំបន់ re-entry និងការប្តូរម៉ូម៉េន tum។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Plots BB bands, EMA stack, and highlight candles when price re-enters the band after expansion.",
    how_it_works_km: "គូស BB EMA stack និងបន្លិចពន្លឺពេលតម្លៃចូល band ឡើងវិញបន្ទាប់ពីពង្រីក។",
    key_features_en: "• Multi-EMA ribbon\n• Re-entry markers\n• Optional alerts on band touch",
    key_features_km: "• Multi-EMA ribbon\n• សញ្ញា re-entry\n• ជូនដំណឹង band touch (ជម្រើស)",
    usage_notes_en: "Best on H1–H4. Combine with higher-timeframe bias from your playbook.",
    usage_notes_km: "សមរម្យ H1–H4។ រួមបញ្ចូល bias timeframe ខ្ពស់ពី playbook។",
    proof_of_testing_en: "Visual backtest review on major FX pairs; not a standalone signal service.",
    proof_of_testing_km: "ពិនិត្យ backtest លើ FX សំខាន់ៗ—មិនមែនសេវាសញ្ញាឯករាជ្យ។",
    image_url: IMAGES[1],
  },
  {
    seed_slug: "session-killzones",
    name: "Session Killzones",
    type: "indicator",
    platform: "MT5",
    pricing: "free",
    version: "1.1.0",
    description_en: "Shade London, New York, and Asia sessions with configurable broker offset and box transparency.",
    description_km: "បន្លិចសម័យ London New York និង Asia ជាមួយការកែ offset broker។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Draws session rectangles on intraday charts using your broker server time.",
    how_it_works_km: "គូសប្រវែងសម័យតាម server time របស់ broker។",
    key_features_en: "• Asia / London / NY boxes\n• Broker GMT offset input\n• Light/dark friendly colors",
    key_features_km: "• ប្រអប់ Asia/London/NY\n• កំណត់ GMT offset\n• ពណ៌សមរម្យ light/dark",
    usage_notes_en: "Set server offset once per broker. Works on M5–H1.",
    usage_notes_km: "កំណត់ server offset ម្តងក្នុងមួយ broker។",
    proof_of_testing_en: "Compared session boxes against exchange calendars for two brokers.",
    proof_of_testing_km: "ប្រៀបធៀបប្រអប់សម័យជាមួយប្រតិទិន exchange។",
    image_url: IMAGES[2],
  },
  {
    seed_slug: "market-structure-pro",
    name: "Market Structure Pro",
    type: "indicator",
    platform: "MT5",
    pricing: "free",
    version: "1.2.0",
    description_en: "Marks swing highs/lows, BOS, and CHoCH with optional HH/HL/LH/LL labels for structure study.",
    description_km: "សម្គាល់ swing BOS CHoCH និង HH/HL/LH/LL សម្រាប់សិក្សារចនាសម្ព័ន្ធ។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Fractal-based swing detection with trend-state coloring.",
    how_it_works_km: "រក swing តាម fractal និងពណ៌តាមស្ថានភាព trend។",
    key_features_en: "• BOS / CHoCH tags\n• Adjustable swing depth\n• Clean minimal objects",
    key_features_km: "• ស្លាក BOS/CHoCH\n• កំហិត swing កែបាន\n• object ស្អាត",
    usage_notes_en: "Increase swing depth on higher timeframes to reduce noise.",
    usage_notes_km: "បង្កើន swing depth លើ timeframe ខ្ពស់ដើម្បីរក្សាសំលេងចុះ។",
    proof_of_testing_en: "Manual chart replay on EURUSD H1 and XAUUSD M15.",
    proof_of_testing_km: "replay chart ដៃគូ EURUSD H1 និង XAUUSD M15។",
    image_url: IMAGES[3],
  },
  {
    seed_slug: "order-block-detector",
    name: "Order Block Detector",
    type: "indicator",
    platform: "MT5",
    pricing: "free",
    version: "1.0.0",
    description_en: "Highlights last opposing candle before impulsive moves—useful for ICT-style study, not auto-trading.",
    description_km: "បន្លិចពន្លឺ candle ប្រឆាំងចុងក្រោយមុនចលនា impulsive—សម្រាប់សិក្សា ICT។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Detects displacement candles and draws the origin block zone.",
    how_it_works_km: "រក displacement និងគូសតំបន់ order block។",
    key_features_en: "• Bullish/bearish blocks\n• Mitigation tracking\n• Max zones limiter",
    key_features_km: "• block bullish/bearish\n• តាមដាន mitigation\n• កំណត់ចំនួន zone",
    usage_notes_en: "Educational overlay only—confirm with your higher-timeframe bias.",
    usage_notes_km: "សម្រាប់សិក្សា—បញ្ជាក់ជាមួយ bias timeframe ខ្ពស់។",
    proof_of_testing_en: "Reviewed zones on XAUUSD M5 during London open samples.",
    proof_of_testing_km: "ពិនិត្យ zone លើ XAUUSD M5 ពេល London open។",
    image_url: IMAGES[4],
  },
  {
    seed_slug: "asian-range-marker",
    name: "Asian Range Marker",
    type: "indicator",
    platform: "MT5",
    pricing: "free",
    version: "1.0.0",
    description_en: "Plots the Asian session high/low range for London breakout context.",
    description_km: "គូស range ខ្ពស់/ទាបសម័យ Asian សម្រាប់ London breakout។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Locks range at session end and extends lines until NY close.",
    how_it_works_km: "ចាក់សោ range ពេលបញ្ចប់សម័យ និងពន្លាតបន្ទាត់រហូត NY close។",
    key_features_en: "• Range high/low lines\n• Midpoint guide\n• Session time inputs",
    key_features_km: "• បន្ទាត់ range high/low\n• មធ្យម midpoint\n• កំណត់ម៉ោងសម័យ",
    usage_notes_en: "Pair with risk rules—breakouts fail often without trend alignment.",
    usage_notes_km: "រួមជាមួយវិន័យហានិភ័យ—breakout បរាជ័យញឹកពេលគ្មាន trend។",
    proof_of_testing_en: "Sampled 30 London days on GBPUSD M15.",
    proof_of_testing_km: "សំណាក ៣០ ថ្ងៃ London លើ GBPUSD M15។",
    image_url: IMAGES[0],
  },
  {
    seed_slug: "liquidity-sweep-alert",
    name: "Liquidity Sweep Alert",
    type: "indicator",
    platform: "MT5",
    pricing: "free",
    version: "1.0.0",
    description_en: "Alerts when price wicks beyond a recent swing and closes back inside—liquidity grab study aid.",
    description_km: "ជូនដំណឹងពេលតម្លៃ wick លើស swing ហើយបិទក្នុង—សិក្សា liquidity grab។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Monitors last N swing levels for sweep-and-reject patterns.",
    how_it_works_km: "តាមដាន swing N ចុងក្រោយសម្រាប់ sweep-and-reject។",
    key_features_en: "• Push / email alerts\n• Adjustable lookback\n• Optional arrow markers",
    key_features_km: "• ជូនដំណឹង push/email\n• lookback កែបាន\n• សញ្ញាព្រួញ (ជម្រើស)",
    usage_notes_en: "Alerts are noisy on M1—prefer M5+.",
    usage_notes_km: "ជូនដំណឹងរំពោរលើ M1—ណែនាំ M5+។",
    proof_of_testing_en: "Alert log reviewed on EURUSD M5 for two weeks.",
    proof_of_testing_km: "ពិនិត្យ log ជូនដំណឹង EURUSD M5 ពីរសប្តាហ៍។",
    image_url: IMAGES[1],
  },
  {
    seed_slug: "fvg-scanner",
    name: "Fair Value Gap Scanner",
    type: "indicator",
    platform: "MT5",
    pricing: "free",
    version: "1.0.0",
    description_en: "Finds three-candle imbalance gaps and shades unfilled zones on the active chart.",
    description_km: "រក FVG បីពន្លឺ និងបន្លិច zone ដែលមិនទាន់បំពេញ។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Scans new bars for bullish/bearish gaps above minimum pip size.",
    how_it_works_km: "ស្កេន bar ថ្មីសម្រាប់ gap bullish/bearish លើស pip អប្បបរមា។",
    key_features_en: "• Min gap filter\n• Mitigation fade\n• Multi-symbol watchlist (chart symbol)",
    key_features_km: "• តម្រង gap\n• រលាយ zone ពេល mitigate\n• តាម symbol លើ chart",
    usage_notes_en: "Gap logic varies by asset—recalibrate min pips for gold vs FX.",
    usage_notes_km: "រូបមន្ត gap ខុសតាម asset—កែ pip សម្រាប់មាស vs FX។",
    proof_of_testing_en: "Compared gaps manually on NAS100 M15 samples.",
    proof_of_testing_km: "ប្រៀបធៀប gap ដៃ NAS100 M15។",
    image_url: IMAGES[2],
  },
  {
    seed_slug: "mtf-dashboard",
    name: "Multi-Timeframe Dashboard",
    type: "indicator",
    platform: "MT5",
    pricing: "free",
    version: "1.3.0",
    description_en: "Compact panel showing trend bias across M15, H1, H4, and D1 using EMA slope agreement.",
    description_km: "បន្ទះតូចបង្ហាញ bias trend M15 H1 H4 D1 តាម EMA slope។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Pulls OHLC from multiple timeframes and scores alignment green/amber/red.",
    how_it_works_km: "ទាញ OHLC ពីច្រើន timeframe និងដាក់ពិន្ទុពណ៌។",
    key_features_en: "• Four-TF matrix\n• Symbol switcher\n• Lightweight CPU use",
    key_features_km: "• ម៉ាត្រីក្សា ៤ TF\n• ប្តូរ symbol\n• ប្រើ CPU តិច",
    usage_notes_en: "Bias tool only—not an entry trigger by itself.",
    usage_notes_km: "ឧបករណ៍ bias ប៉ុណ្ណោះ—មិនមែនសញ្ញាចូលឯករាជ្យ។",
    proof_of_testing_en: "Panel compared to manual EMA stack on 12 symbols.",
    proof_of_testing_km: "ប្រៀបធៀបបន្ទះជាមួយ EMA stack ដៃ ១២ symbol។",
    image_url: IMAGES[3],
  },
  {
    seed_slug: "spread-monitor",
    name: "Spread Monitor",
    type: "indicator",
    platform: "MT5",
    pricing: "free",
    version: "1.0.0",
    description_en: "Live spread, average spread, and warning when spread exceeds your pip threshold.",
    description_km: "spread ផ្ទាល់ មធ្យម និងព្រមានពេលលើស pip ដែលអ្នកកំណត់។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Reads Ask/Bid each tick and maintains a rolling session average.",
    how_it_works_km: "អាន Ask/Bid រៀងរាល់ tick និងគណនាមធ្យមសម័យ។",
    key_features_en: "• Max spread alert\n• Session average\n• Corner HUD display",
    key_features_km: "• ព្រមាន spread អតិបរមា\n• មធ្យមសម័យ\n• HUD មុំអេក្រង់",
    usage_notes_en: "Set thresholds per symbol—gold spreads differ from majors.",
    usage_notes_km: "កំណត់ threshold តាម symbol។",
    proof_of_testing_en: "Validated against Market Watch spread during news windows.",
    proof_of_testing_km: "ផ្ទៀងផ្ទាត់ជាមួយ Market Watch ពេលព័ត៌មាន។",
    image_url: IMAGES[4],
  },
  {
    seed_slug: "pivot-points-auto",
    name: "Pivot Points Auto",
    type: "indicator",
    platform: "MT5",
    pricing: "free",
    version: "1.0.0",
    description_en: "Daily/weekly pivot, S1–S3, R1–R3 with classic floor-trader formula.",
    description_km: "Pivot ប្រចាំថ្ងៃ/សប្តាហ៍ S1–S3 R1–R3 រូបមន្ត classic។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Calculates levels from prior period OHLC at broker midnight.",
    how_it_works_km: "គណនាពី OHLC កាលពីមុនតាម midnight broker។",
    key_features_en: "• Daily & weekly modes\n• Line labels\n• Low object count",
    key_features_km: "• របៀបថ្ងៃ/សប្តាហ៍\n• ស្លាកបន្ទាត់\n• object តិច",
    usage_notes_en: "Confirm pivot session matches your broker day open.",
    usage_notes_km: "បញ្ជាក់ session pivot ត្រូវនឹងថ្ងៃបើក broker។",
    proof_of_testing_en: "Levels matched spreadsheet pivots on EURUSD.",
    proof_of_testing_km: "បន្ទាត់ត្រូវ spreadsheet EURUSD។",
    image_url: IMAGES[0],
  },
  {
    seed_slug: "goldmesh-ea",
    name: "GoldMesh EA",
    type: "ea",
    platform: "MT5",
    pricing: "free",
    version: "2.0.0",
    description_en:
      "Grid-style EA for XAUUSD study only—staggered entries with configurable lot steps. High risk; demo first.",
    description_km:
      "EA បែប grid សម្រាប់សិក្សា XAUUSD—ចូលជាជំហាន lot កំណត់បាន។ ហានិភ័យខ្ពស់ សាក demo ជាមុន។",
    requirements_en: MT5_REQ_EN + " VPS recommended. Minimum $500 demo for lot testing.",
    requirements_km: MT5_REQ_KM + " ណែនាំ VPS និង demo $500+។",
    how_it_works_en: "Places a buy grid with distance and multiplier inputs; optional sell leg delayed.",
    how_it_works_km: "ដាក់ buy grid ជាមួយចម្ងាយ និង multiplier ជម្រើស sell ពន្យាពេល។",
    key_features_en: "• Lot multiplier cap\n• Max grid depth\n• Equity stop input",
    key_features_km: "• កំណត់ multiplier\n• ជម្រៅ grid អតិបរមា\n• equity stop",
    usage_notes_en: "Educational EA—not financial advice. Never run unmonitored on live.",
    usage_notes_km: "EA សិក្សា—មិនមែនដំបូន្មានហិរញ្ញវត្ថុ។ កុំដំណើរការ live មិនមើល។",
    proof_of_testing_en: "Demo forward test on XAUUSD M5; max drawdown logged over 4 weeks.",
    proof_of_testing_km: "forward test demo XAUUSD M5 រយៈ ៤ សប្តាហ៍។",
    image_url: IMAGES[1],
  },
  {
    seed_slug: "break-even-assistant",
    name: "Break-Even Assistant",
    type: "ea",
    platform: "MT5",
    pricing: "free",
    version: "1.0.0",
    description_en: "Moves stop to entry after price reaches +R (configurable) on manual trades.",
    description_km: "ផ្លាស់ stop ទៅ entry ពេលតម្លៃឈានដល់ +R លើប្រតិបត្តិការដៃ។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Monitors open positions with magic number 0 (manual) or a custom magic.",
    how_it_works_km: "តាមដាន position បើក magic 0 ឬ magic កំណត់។",
    key_features_en: "• R-based trigger\n• Optional partial lock\n• One-chart manages all symbols",
    key_features_km: "• trigger +R\n• lock ផ្នែក (ជម្រើស)\n• chart តែមួយគ្រប់ symbol",
    usage_notes_en: "Set R from initial stop distance at order placement.",
    usage_notes_km: "កំណត់ R ពីចម្ងាយ stop ដើម។",
    proof_of_testing_en: "Demo test on EURUSD manual scalps.",
    proof_of_testing_km: "សាក demo EURUSD scalp ដៃ។",
    image_url: IMAGES[2],
  },
  {
    seed_slug: "partial-close-manager",
    name: "Partial Close Manager",
    type: "ea",
    platform: "MT5",
    pricing: "free",
    version: "1.0.0",
    description_en: "Closes 50% at TP1 and trails remainder—designed for manual trade management.",
    description_km: "បិទ ៥០% នៅ TP1 និង trail ផ្នែកនៅសល់—គ្រប់គ្រងប្រតិបត្តិការដៃ។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Watches positions; at pip target closes fraction then enables trail stop.",
    how_it_works_km: "តាមដាន position បិទផ្នែកនៅ pip គោលដៅ រួច trail។",
    key_features_en: "• TP1 percent close\n• Trail step pips\n• Magic filter",
    key_features_km: "• បិទ TP1 %\n• trail step pip\n• តម្រង magic",
    usage_notes_en: "Works best when initial TP is far; adjust partial percent per playbook.",
    usage_notes_km: "សមរម្យពេល TP ដើមឆ្ងាយ។",
    proof_of_testing_en: "Demo runs on XAUUSD swing trades.",
    proof_of_testing_km: "សាក demo XAUUSD swing។",
    image_url: IMAGES[3],
  },
  {
    seed_slug: "news-pause-guard",
    name: "News Pause Guard",
    type: "ea",
    platform: "MT5",
    pricing: "free",
    version: "1.0.0",
    description_en: "Blocks new EA entries ±N minutes around a daily time window you set (manual news calendar).",
    description_km: "បិទចូល EA ថ្មី ±N នាទីជុំវិញម៉ោងដែលអ្នកកំណត់ (ប្រតិទិនដៃ)។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Other EAs check global variable; this EA sets pause flag during window.",
    how_it_works_km: "EA ផ្សេងពិនិត្យ global variable ពេល pause។",
    key_features_en: "• Up to 3 daily windows\n• Minutes before/after\n• Chart status label",
    key_features_km: "• រហូត ៣ បង្អួច/ថ្ងៃ\n• នាទីមុន/ក្រោយ\n• ស្លាកស្ថានភាព",
    usage_notes_en: "You must update windows when economic calendar changes.",
    usage_notes_km: "ត្រូវកែបង្អួចពេលប្រតិទិនផ្លាស់ប្តូរ។",
    proof_of_testing_en: "Verified pause flag blocks test EA entries on demo.",
    proof_of_testing_km: "ផ្ទៀងផ្ទាត់ pause បិញ test EA នៅ demo។",
    image_url: IMAGES[4],
  },
  {
    seed_slug: "trailing-stop-engine",
    name: "Trailing Stop Engine",
    type: "ea",
    platform: "MT5",
    pricing: "free",
    version: "1.1.0",
    description_en: "ATR-based trailing stop for manual positions—tightens only in profit.",
    description_km: "Trailing stop តាម ATR សម្រាប់ position ដៃ—រឹតតែពេលចំណេញ។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Recalculates stop each bar using ATR multiplier from extreme price.",
    how_it_works_km: "គណនា stop រៀងរាល់ bar តាម ATR ពីតម្លៃកំពូល/បាត។",
    key_features_en: "• ATR period & mult\n• Start-after-pips\n• Never widen stop",
    key_features_km: "• ATR period/mult\n• ចាប់ trail ក្រោយ pip\n• មិនពង្រីក stop",
    usage_notes_en: "Increase ATR mult on volatile gold.",
    usage_notes_km: "បង្កើន ATR mult លើមាសញឹកញាប់។",
    proof_of_testing_en: "Compared trail distance to manual ATR on H1 swings.",
    proof_of_testing_km: "ប្រៀបធៀប trail ជាមួយ ATR ដៃ H1។",
    image_url: IMAGES[0],
  },
  {
    seed_slug: "risk-guard-ea",
    name: "Risk Guard EA",
    type: "ea",
    platform: "MT5",
    pricing: "free",
    version: "1.0.0",
    description_en: "Daily loss limit and max open risk—closes all and disables trading when breached.",
    description_km: "កំណត់ខាតប្រចាំថ្ងៃ និងហានិភ័យបើក—បិទទាំងអស់ពេលលើស។",
    requirements_en: MT5_REQ_EN,
    requirements_km: MT5_REQ_KM,
    how_it_works_en: "Tracks floating + closed P/L from broker midnight; trips circuit breaker.",
    how_it_works_km: "តាមដាន P/L ពី midnight broker និង trip breaker។",
    key_features_en: "• Daily % loss cap\n• Max concurrent risk %\n• Email/push on trip",
    key_features_km: "• កំណត់ខាត % ថ្ងៃ\n• ហានិភ័យបើក %\n• ជូនដំណឹង trip",
    usage_notes_en: "Set conservative limits on demo before live.",
    usage_notes_km: "កំណត់កំហិតរឹតនៅ demo មុន live។",
    proof_of_testing_en: "Tripped correctly on demo after forced loss sequence.",
    proof_of_testing_km: "trip ត្រឹមត្រូវនៅ demo ក្រោយខាតជំរុញ។",
    image_url: IMAGES[1],
  },
];

export const TOOLS_SEED_COUNT = toolsData.length;
